name: health_nest
description: A comprehensive health and fitness application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    google_fonts: ^6.2.1
  
  # State Management
  provider: ^6.1.2

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.5
  cloud_firestore: ^4.13.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.0.0 # Updated version
  
  # UI/Icons/Utilities
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  
  # Health & Fitness
  pedometer: ^4.1.1
  
  # Data Handling & Formatting
  intl: ^0.19.0 # Updated version
  fl_chart: ^0.66.2 # Updated version

  # Other
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Updated version

flutter:
  uses-material-design: true