#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔥 FIRESTORE INDEX SETUP - HEALTHNEST"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT:${NC} Firebase does not allow programmatic index creation."
echo -e "   You MUST create indexes manually via Firebase Console."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}METHOD 1: AUTO-CREATE VIA ERROR URL (FASTEST - 30 seconds)${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Run your app:"
echo -e "   ${BLUE}flutter run -d chrome${NC}"
echo ""
echo "2. Login to your app"
echo ""
echo "3. Navigate to: Pregnancy Tracker → Bump Photos"
echo ""
echo "4. Open browser console (F12)"
echo ""
echo "5. Look for error message containing URL like:"
echo -e "   ${YELLOW}https://console.firebase.google.com/v1/r/project/...${NC}"
echo ""
echo "6. Click the URL → Firebase Console opens with pre-filled config"
echo ""
echo "7. Click 'CREATE INDEX' button"
echo ""
echo "8. Wait 1-2 minutes → Done! ✅"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}METHOD 2: MANUAL CREATION VIA FIREBASE CONSOLE${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Open Firebase Console:"
echo -e "   ${BLUE}https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes${NC}"
echo ""
echo "2. Click 'CREATE INDEX' button (top right)"
echo ""
echo "3. Create the following 4 indexes:"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}INDEX 1: bump_photos${NC} (CRITICAL - Blocks photo display)"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "Collection ID: bump_photos"
echo "Query scope:   Collection"
echo "Fields:"
echo "  • userId       → Ascending"
echo "  • pregnancyId  → Ascending"
echo "  • week         → Ascending"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}INDEX 2: symptom_logs${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "Collection ID: symptom_logs"
echo "Query scope:   Collection"
echo "Fields:"
echo "  • pregnancyId  → Ascending"
echo "  • logDate      → Descending"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}INDEX 3: kick_counts${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "Collection ID: kick_counts"
echo "Query scope:   Collection"
echo "Fields:"
echo "  • pregnancyId  → Ascending"
echo "  • startTime    → Descending"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}INDEX 4: contractions${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "Collection ID: contractions"
echo "Query scope:   Collection"
echo "Fields:"
echo "  • pregnancyId  → Ascending"
echo "  • startTime    → Descending"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${GREEN}AFTER CREATING INDEXES:${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Wait 1-2 minutes for indexes to build"
echo ""
echo "2. Check status in Firebase Console → Indexes tab"
echo "   Status should change from 'Building' → 'Enabled'"
echo ""
echo "3. Restart your Flutter app"
echo ""
echo "4. Navigate to Pregnancy Tracker → Bump Photos"
echo ""
echo "5. ✅ Photos will now appear in the list!"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${BLUE}QUICK VERIFICATION:${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Check if indexes exist:"
echo -e "  ${BLUE}firebase firestore:indexes${NC}"
echo ""
echo "View current indexes:"
echo -e "  ${BLUE}https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes${NC}"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo -e "${YELLOW}📋 SUMMARY:${NC}"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo -e "✅ Image upload:        ${GREEN}Working perfectly${NC}"
echo -e "✅ Supabase storage:    ${GREEN}Working perfectly${NC}"
echo -e "✅ Metadata saved:      ${GREEN}Working perfectly${NC}"
echo -e "❌ Photo list display:  ${RED}Waiting for index${NC}"
echo ""
echo -e "🎯 ${YELLOW}Action required:${NC} Create bump_photos index (2 minutes)"
echo ""
echo "═══════════════════════════════════════════════════════════════"

# Open Firebase Console automatically
echo ""
read -p "Press ENTER to open Firebase Console, or Ctrl+C to cancel..."
echo ""
echo "Opening Firebase Console..."

# Try to open browser
if command -v xdg-open &> /dev/null; then
    xdg-open "https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes"
elif command -v open &> /dev/null; then
    open "https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes"
elif command -v google-chrome &> /dev/null; then
    google-chrome "https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes"
elif command -v firefox &> /dev/null; then
    firefox "https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes"
else
    echo "Could not open browser automatically."
    echo "Please open this URL manually:"
    echo "https://console.firebase.google.com/project/healthnest-ae7bb/firestore/indexes"
fi

echo ""
echo -e "${GREEN}✅ Done! Follow the instructions above to create indexes.${NC}"
echo ""
