// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACU-kMBtoDZ0NHDg3KsI9-u2uq6xZZ0ZM',
    appId: '1:66898048685:web:e1c2f138c5be82eb34f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    authDomain: 'healthnest-ae7bb.firebaseapp.com',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
    measurementId: 'G-M5G4MDX82Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6M0_ZL4EKtwUJ1ieuUfW-zq--sFzkm8',
    appId: '1:66898048685:android:97479e97c570f09634f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-AgHA4ljFikOVlGh65m4ZAp0kgA0OBc',
    appId: '1:66898048685:ios:a4fcc4553cd05c3334f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
    iosBundleId: 'com.example.healthNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-AgHA4ljFikOVlGh65m4ZAp0kgA0OBc',
    appId: '1:66898048685:ios:a4fcc4553cd05c3334f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
    iosBundleId: 'com.example.healthNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACU-kMBtoDZ0NHDg3KsI9-u2uq6xZZ0ZM',
    appId: '1:66898048685:web:4d64f2d873030d3934f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    authDomain: 'healthnest-ae7bb.firebaseapp.com',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
    measurementId: 'G-QM82WZQZSD',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyACU-kMBtoDZ0NHDg3KsI9-u2uq6xZZ0ZM',
    appId: '1:66898048685:web:4d64f2d873030d3934f824',
    messagingSenderId: '66898048685',
    projectId: 'healthnest-ae7bb',
    authDomain: 'healthnest-ae7bb.firebaseapp.com',
    storageBucket: 'healthnest-ae7bb.firebasestorage.app',
    measurementId: 'G-QM82WZQZSD',
  );
}
